yml file

diff --git a/.github/workflows/testTags.yml b/.github/workflows/testTags.yml
--- a/.github/workflows/testTags.yml
+++ b/.github/workflows/testTags.yml
@@ -1,154 +1,154 @@
 
-name: Deploy Changes and Rollback
-on:
-  workflow_call:
-  push:
-    tags:
-      - 'v*.*.*'
-  release:
-    types: [created, deleted]
-# TODO: 
-# - Check to see if you can run jobs depending on trigger event
-jobs:
-# Get the latest Tag's branch and store into variable 
-  get-branch:
-    runs-on: ubuntu-latest
-    outputs: 
-      bName: ${{steps.branch-name.outputs.branchN}}
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          fetch-depth: 0
-      - name: Get Branch From Tag
-        id: branch-name
-        run: |
-          tag=${{github.ref_name}}
-          raw=$(git branch -r --contains ${{ github.ref }})
-          branch=${raw/origin\/}
-          echo "branchN=$branch" >> $GITHUB_OUTPUT
-          echo "Branch is $branch"
-          tagStripped=${tag/v1\/}
-          echo "Tag is $tag"
-          echo "Tag Stripped is $tagStripped"
-          echo "Event that triggered it is ${{github.event_name}}"
-  debug:
-    needs: get-branch
-    runs-on: ubuntu-latest
-    steps:
-      - name: Debug output
-        run: |
-          echo "${{ toJson(needs.get-branch) }}"
-  prod-test:
-    needs: get-branch
-    runs-on: ubuntu-latest
-    steps:
-      - name: Debug output
-        run: |
-          echo "${{ github.event_name }}"
+# name: Deploy Changes and Rollback
+# on:
+#   workflow_call:
+#   push:
+#     tags:
+#       - 'v*.*.*'
+#   release:
+#     types: [created, deleted]
+# # TODO: 
+# # - Check to see if you can run jobs depending on trigger event
+# jobs:
+# # Get the latest Tag's branch and store into variable 
+#   get-branch:
+#     runs-on: ubuntu-latest
+#     outputs: 
+#       bName: ${{steps.branch-name.outputs.branchN}}
+#     steps:
+#       - uses: actions/checkout@v2
+#         with:
+#           fetch-depth: 0
+#       - name: Get Branch From Tag
+#         id: branch-name
+#         run: |
+#           tag=${{github.ref_name}}
+#           raw=$(git branch -r --contains ${{ github.ref }})
+#           branch=${raw/origin\/}
+#           echo "branchN=$branch" >> $GITHUB_OUTPUT
+#           echo "Branch is $branch"
+#           tagStripped=${tag/v1\/}
+#           echo "Tag is $tag"
+#           echo "Tag Stripped is $tagStripped"
+#           echo "Event that triggered it is ${{github.event_name}}"
+#   debug:
+#     needs: get-branch
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Debug output
+#         run: |
+#           echo "${{ toJson(needs.get-branch) }}"
+#   prod-test:
+#     needs: get-branch
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Debug output
+#         run: |
+#           echo "${{ github.event_name }}"
 
-# Check that tag is on correct branch
-  check-tag-with-branch:
-    needs: get-branch
-    runs-on: ubuntu-latest
-    if: |
-      (contains(github.event_name, 'push')) &&
-      (needs.get-branch.outputs.bName == '  main' && !(contains(github.ref_name, '-main'))) ||
-      (needs.get-branch.outputs.bName == '  feature1' && !(contains(github.ref_name, '-feature1')))
-    steps:
-      - name: Message
-        run: |
-          echo "Changes not deployed!!"
-          echo "${{github.ref_name}} does not belong with${{needs.gtTB.outputs.bName}} branch!"
-          exit 1
-# If tag is on prod exit with no error code and do the release event handling
+# # Check that tag is on correct branch
+#   check-tag-with-branch:
+#     needs: get-branch
+#     runs-on: ubuntu-latest
+#     if: |
+#       (contains(github.event_name, 'push')) &&
+#       (needs.get-branch.outputs.bName == '  main' && !(contains(github.ref_name, '-main'))) ||
+#       (needs.get-branch.outputs.bName == '  feature1' && !(contains(github.ref_name, '-feature1')))
+#     steps:
+#       - name: Message
+#         run: |
+#           echo "Changes not deployed!!"
+#           echo "${{github.ref_name}} does not belong with${{needs.gtTB.outputs.bName}} branch!"
+#           exit 1
+# # If tag is on prod exit with no error code and do the release event handling
 
 
-# Depending on what branch do an autoscale refresh to that environment,
-# If brannch = stage
-  # Refresh to stage environment
-# If branch = develop
-  # Refresh to Develop
-# If branch = main
-  # Refresh to Production  
-# ___________________________________________________________________
+# # Depending on what branch do an autoscale refresh to that environment,
+# # If brannch = stage
+#   # Refresh to stage environment
+# # If branch = develop
+#   # Refresh to Develop
+# # If branch = main
+#   # Refresh to Production  
+# # ___________________________________________________________________
 
-# possible to add check-tag... job into the needs
-  main-refresh:
-    runs-on: ubuntu-latest
-    needs: get-branch
-    if: ${{ contains(github.ref_name, 'main') && needs.get-branch.outputs.bName == '  main' }}
-    steps:
-    - name: Configure AWS credentials
-      id: aws-credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-west-1
+# # possible to add check-tag... job into the needs
+#   main-refresh:
+#     runs-on: ubuntu-latest
+#     needs: get-branch
+#     if: ${{ contains(github.ref_name, 'main') && needs.get-branch.outputs.bName == '  main' }}
+#     steps:
+#     - name: Configure AWS credentials
+#       id: aws-credentials
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: us-west-1
 
-    - name: 'Get value from Parameter Store'
-      id: parameter
-      uses: poad/get-aws-ssm-parameter@v1.0.0
-      with: 
-        parameter-name: /mainRefresh
-        aws-region: us-west-1
+#     - name: 'Get value from Parameter Store'
+#       id: parameter
+#       uses: poad/get-aws-ssm-parameter@v1.0.0
+#       with: 
+#         parameter-name: /mainRefresh
+#         aws-region: us-west-1
   
-    - name: 'Another example step'
-      run: echo " Refreshing- ${{ steps.parameter.outputs.value }} "
+#     - name: 'Another example step'
+#       run: echo " Refreshing- ${{ steps.parameter.outputs.value }} "
 
-  feature1-refresh:
-    runs-on: ubuntu-latest
-    needs: get-branch
-    if: ${{ contains(github.ref_name, 'feature1')  && needs.get-branch.outputs.bName == '  feature1'}}
-    steps:
-    - name: Configure AWS credentials
-      id: aws-credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-west-1
+#   feature1-refresh:
+#     runs-on: ubuntu-latest
+#     needs: get-branch
+#     if: ${{ contains(github.ref_name, 'feature1')  && needs.get-branch.outputs.bName == '  feature1'}}
+#     steps:
+#     - name: Configure AWS credentials
+#       id: aws-credentials
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: us-west-1
 
-    - name: 'Get value from Parameter Store'
-      id: parameter
-      uses: poad/get-aws-ssm-parameter@v1.0.0
-      with: 
-        parameter-name: /featureRefresh
-        aws-region: us-west-1
+#     - name: 'Get value from Parameter Store'
+#       id: parameter
+#       uses: poad/get-aws-ssm-parameter@v1.0.0
+#       with: 
+#         parameter-name: /featureRefresh
+#         aws-region: us-west-1
   
-    - name: 'Another example step'
-      run: echo " Refreshing- ${{ steps.parameter.outputs.value }} "
+#     - name: 'Another example step'
+#       run: echo " Refreshing- ${{ steps.parameter.outputs.value }} "
 
 
 
-# If tests are a success - update last working commit on param store
-# Else
-  # Grab the latest commit from param store
-  # Call workflow again
-  # Refresh with this last working commit 
-# _______________________________________________________________________
-  get-latest-stable-commit:
-    runs-on: ubuntu-latest
-    steps:
-    - name: Configure AWS credentials
-      id: aws-credentials
-      uses: aws-actions/configure-aws-credentials@v1
-      with:
-        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        aws-region: us-west-1
+# # If tests are a success - update last working commit on param store
+# # Else
+#   # Grab the latest commit from param store
+#   # Call workflow again
+#   # Refresh with this last working commit 
+# # _______________________________________________________________________
+#   get-latest-stable-commit:
+#     runs-on: ubuntu-latest
+#     steps:
+#     - name: Configure AWS credentials
+#       id: aws-credentials
+#       uses: aws-actions/configure-aws-credentials@v1
+#       with:
+#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#         aws-region: us-west-1
 
-    - name: 'Get value from Parameter Store'
-      id: parameter
-      uses: poad/get-aws-ssm-parameter@v1.0.0
-      with: 
-        parameter-name: /stableCommit
-        aws-region: us-west-1
+#     - name: 'Get value from Parameter Store'
+#       id: parameter
+#       uses: poad/get-aws-ssm-parameter@v1.0.0
+#       with: 
+#         parameter-name: /stableCommit
+#         aws-region: us-west-1
   
-    - name: 'Another example step'
-      run: echo ${{ steps.parameter.outputs.value }}
+#     - name: 'Another example step'
+#       run: echo ${{ steps.parameter.outputs.value }}
 
 
-# If tests failed and release event, delete the latest release
-# Should trigger workflow again since we are listening on this and rerun
+# # If tests failed and release event, delete the latest release
+# # Should trigger workflow again since we are listening on this and rerun
 
